# Workflow para fazer build e deploy de um site Angular no GitHub Pages
name: Deploy Angular Site to Pages

on:
  # Roda quando um push é feito para a branch `main`
  push:
    branches: ["main"]

  # Permite rodar este workflow manualmente pela aba Actions
  workflow_dispatch:

# Define as permissões para o token do GitHub Actions
permissions:
  contents: read
  pages: write
  id-token: write

# Define um deploy concorrente para que apenas o mais recente seja executado
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de build
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18" # Use a versão do Node que preferir
          cache: "npm"
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build -- --base-href /${{ github.event.repository.name }}/
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Pasta que o Angular gera o build
          path: './dist/milhiolo_workshop/browser'

  # Job de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
